In [1]:
import numpy as np

In [19]:
data = np.random.randn(3, 5)
slice_param = [0, 3, 0, 2]#вказуємо розмірність "обрізаної" матриці

In [20]:
class Fumo:
    
    def __init__(self):
        return 0
    
    def cut_matrix(data, slice_param):
        x1, x2, y1, y2 = slice_param
        new_matrix = data[x1:x2, y1:y2]
        return new_matrix
    
    def absolute_value(new_matrix):
        return np.abs(new_matrix)
        
    def root(new_matrix):
        x = np.abs(new_matrix)
        return np.sqrt(x)
    
    def power_2(new_matrix):
        return np.square(new_matrix)
    
    def exponential(new_matrix):
        return np.exp(new_matrix)
    
    def logs(new_matrix):
        return np.log(new_matrix), np.log10(new_matrix), np.log2(new_matrix), np.log1p(new_matrix)
    
    def sign(new_matrix):
        return np.sign(new_matrix)
    
    def lowest_whole(new_matrix):
        return np.floor(new_matrix)
    
    def est(new_matrix):
        return np.rint(new_matrix)
    
    def split_val(new_matrix):
        return np.modf(new_matrix)
    
    def NaN(new_matrix):
        return np.isnan(new_matrix)
    
    def fin_inf(new_matrix):
        return np.isfinite(new_matrix), np.isinf(new_matrix)
    
    def trigonometry(new_matrix):
        return np.cos(new_matrix), np.sin(new_matrix), np.tan(new_matrix), np.cosh(new_matrix), np.sinh(new_matrix), np.tanh(new_matrix)
    
    def rev_trigonometry(new_matrix):
        return np.arccos(new_matrix), np.arcsin(new_matrix), np.arctan(new_matrix), np.arccosh(new_matrix), np.arcsinh(new_matrix), np.arctanh(new_matrix)
    
    def is_not(new_matrix):
        return np.logical_not(new_matrix)

In [30]:
new_matrix = Fumo.cut_matrix(data, slice_param)
print(Fumo.absolute_value(new_matrix))
print(Fumo.root(new_matrix))
print(Fumo.power_2(new_matrix))
print(Fumo.exponential(new_matrix))
#print(Fumo.logs(new_matrix))
print(Fumo.sign(new_matrix))
print(Fumo.lowest_whole(new_matrix))
print(Fumo.est(new_matrix))
print(Fumo.split_val(new_matrix))
print(Fumo.NaN(new_matrix))
print(Fumo.fin_inf(new_matrix))
#print(Fumo.trigonometry(new_matrix))
#print(Fumo.rev_trigonometry(new_matrix))
print(Fumo.is_not(new_matrix))

[[0.88618042 0.09899598]
 [0.160424   0.04773687]
 [0.85070357 0.83741955]]
[[0.94137156 0.31463626]
 [0.40052964 0.21848769]
 [0.92233593 0.9151063 ]]
[[0.78531573 0.0098002 ]
 [0.02573586 0.00227881]
 [0.72369656 0.7012715 ]]
[[2.42584621 1.10406186]
 [1.17400854 0.95338462]
 [0.42711432 0.43282597]]
[[ 1.  1.]
 [ 1. -1.]
 [-1. -1.]]
[[ 0.  0.]
 [ 0. -1.]
 [-1. -1.]]
[[ 1.  0.]
 [ 0. -0.]
 [-1. -1.]]
(array([[ 0.88618042,  0.09899598],
       [ 0.160424  , -0.04773687],
       [-0.85070357, -0.83741955]]), array([[ 0.,  0.],
       [ 0., -0.],
       [-0., -0.]]))
[[False False]
 [False False]
 [False False]]
(array([[ True,  True],
       [ True,  True],
       [ True,  True]]), array([[False, False],
       [False, False],
       [False, False]]))
[[False False]
 [False False]
 [False False]]


In [32]:
np.repeat(new_matrix, 4, 1)

array([[ 0.88618042,  0.88618042,  0.88618042,  0.88618042,  0.09899598,
         0.09899598,  0.09899598,  0.09899598],
       [ 0.160424  ,  0.160424  ,  0.160424  ,  0.160424  , -0.04773687,
        -0.04773687, -0.04773687, -0.04773687],
       [-0.85070357, -0.85070357, -0.85070357, -0.85070357, -0.83741955,
        -0.83741955, -0.83741955, -0.83741955]])